### ISSUE TITLE
Explain what the device-proxy program is/does/why it exists.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/entropy-docs#200]
The device-proxy is an Entropy program available at `0000000000000000000000000000000000000000000000000000000000000000` and _does stuff_.

## Tasks

- [x] What is it?
- [x] What does it do?

Allows you to bind or constrain requires you to have a secondary signature of any public key.

Easier way: it allows you to have multiple accounts to control a key.

- [ ] What problems does it solve?
- [ ] Who should interact with it?

I guess everyone. But mostly external program devs.

- [ ] How should one interact with it?
- [ ] Any troubleshooting tip/tricks/gotchas readers should know about.
