### ISSUE TITLE
Create "programs" section.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/entropy-docs#269]
Entropy programs exist, and they're a huge part of the network. Correctly designing and implementing Entropy programs is crucial. It's also the only way that devs can use Entropy.

To do this, we likely need to create a new section within the docs _just_ for Programs. This new section needs to explain the following:

- [x] What programs are (and what they're not) https://github.com/entropyxyz/entropy-docs/issues/295
    - [x] What they're _made of_ (WASM)
    - [x] Who's gonna interact with them (validators)
    - [x] What they can do (generate a signature to the validators, or fail)
    - [x] What they can't do (interact with non-deterministic data, return a result other than a signature or failure)
    - [x] Program lifecycle (how are they made, read, updated, and deleted).
- [ ] How to:
    - [ ] Create
    - [ ] Deploy
    - [ ] Test programs on the testnet
    - [ ] Maintain (update and delete)
    - [ ] Use (get validators to generate a signature using a particular program)
- [ ] Current issues with programs (stuff we know programs can't do right now, but will be able to do in the future).

This issue is a work-in-progress.

## Sub-issues

- https://github.com/entropyxyz/entropy-docs/issues/275
