### ISSUE TITLE
Refactor files and sidebar to accomodate the new Programs section.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/entropy-docs#275]
The sidebar and underlying docs content need moving around to reflect the upcoming Programs section (see https://github.com/entropyxyz/entropy-docs/issues/269).

## Tasks:

- [x] Review and analyze existing structure.
- [x] Update Markdown to fit new structure.
- [x] Review and update cross-linking and references.

```plaintext
Mechanics:
- What they're made of (WASM)
- Who's gonna interact with them (validators)
- What they can do (generate a signature to the validators, or fail)
- What they can't do (interact with non-deterministic data, return a result other than a signature or failure)
- Program lifecycle (how are they made, read, updated, and deleted).

Development
- Create
- Deploy
- Update
- Delete

Testing

Troubleshooting
```

**Comment by johnnymatthews** [comment]
Merged into #269.
